language: node_js
node_js:
- '4.2'
before_script:
- rvm install 2.2.3
- bundle install
script:
- npm run lint
- bundle exec rake test
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  slack:
    secure: MmlQrKMvbqzj3fWoPQoRh3sbYWS3U08d3ggawKledL4uaeBoc9B+35Pp9uYDgqzzE/1SAiWhQ8UIa+DT0Ya6P2DlEPNoCo4YLQn7jq+Rjd7aaG1K8DRfldn1il7mxnw4nHifANWUOJlxdjMiWplUbTsh4o7Tgd/M4GS3Cin8UPvqAECwovJhseFZQyCaz843Y78AatY6yYADHYItqxnBVM+GmvqC4DVhl0k8wvqX5x3EKO7NHrMNUx9YNL4mwyWQBhKWpgquqZuPOqJQUTU0p9Br6FSZ1JzQMmPb3PcwimxmNQsE9OxT/NoNNazkGbgY4JrNsJ3bj1LgqIe3+E7a+LSIEyEVtQenGBJ1m7lk/ihqd4i5u2f20baH6RKKTRYWqKqDXzIJ5Hs85Tgvn1uaMABqRkrK8hMKKiQyNxwF5Fpj9YjPFXBoi9oAK/NjcH8nWL2kyobOCXLWQdpzJgAGQjRoFL5RGjiTxuIA/jATNbUorIXgpkAoB42WFqvJtqOwyLVv/IfZ5FudBEZr1mrc2EXOZKGlOdtY2JJebtx5ADNSeg+fPMez1ogl3gAfvQhk4YWxyvVKaq8+lu94Ne/xE1e0u7c6nKwZLSJXOF7yLPy9djnLsYy/SjY29SbVcn+WJRECjE/9PuclXr1UP4NPzsXzjyFAFC44254zgZT13aw=
